Added new error & hard stop if workspace identity ID cannot be determined. Added output for workspace identity to help with debugging.

diff --git a/.github/workflows/deploy-fabric-accelerator.yml b/.github/workflows/deploy-fabric-accelerator.yml
--- a/.github/workflows/deploy-fabric-accelerator.yml
+++ b/.github/workflows/deploy-fabric-accelerator.yml
@@ -115,12 +115,14 @@ jobs:
 
             wIObjId=$(fab ls "${WORKSPACE_NAME}.Workspace/.managedidentities" -l | grep "${WORKSPACE_NAME}.ManagedIdentity" | awk '{print $2}' | tr -d '\r\n')
            
-            fab acl get "${WORKSPACE_NAME}.Workspace"
-            echo "wIObjId=$wIObjId"
-            fab ls "${WORKSPACE_NAME}.Workspace/.managedidentities"
+            wIObjId=$(...)
+            echo "wIObjId='$wIObjId'"
+            if [ -z "$wIObjId" ]; then
+              echo "ERROR: Workspace identity ID could not be determined"
+                exit 1
+              fi
 
-            fab ls "${WORKSPACE_NAME}.Workspace/.managedidentities" --output_format json
-            fab acl get "${WORKSPACE_NAME}.Workspace" --output_format json
+            fab get "${WORKSPACE_NAME}.Workspace/.managedidentities/${WORKSPACE_NAME}.ManagedIdentity" --output_format json
 
             fab acl get "${WORKSPACE_NAME}.Workspace" -q "[?principal.servicePrincipalDetails.aadAppId=='${wIObjId}'] | length(@)" | grep -q '^[1-9]' \
               && echo "Workspace identity already has an ACL in workspace" \
